#!/usr/bin/env bash

[[ $# -ne 1 ]] && 
    echo "ERR > \$# must be equal to 1" &&
    echo "CCV > $0 COMMIT_NAME_ARG" && 
    exit 1

git pull
git add -A
git status
git commit -a -m "$1"
git push -u origin master
